# Generated by Django 5.2.4 on 2025-07-25 22:54

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DockerHost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "host_type",
                    models.CharField(
                        choices=[("tcp", "TCP"), ("unix", "Unix Socket")],
                        default="unix",
                        max_length=10,
                    ),
                ),
                (
                    "connection_string",
                    models.CharField(
                        help_text="e.g., tcp://192.168.1.100:2376 or unix:///var/run/docker.sock",
                        max_length=500,
                    ),
                ),
                ("tls_enabled", models.BooleanField(default=False)),
                ("tls_verify", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Docker Host",
                "verbose_name_plural": "Docker Hosts",
            },
        ),
        migrations.CreateModel(
            name="ContainerJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("override_command", models.TextField(blank=True)),
                (
                    "override_environment",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional or override environment variables",
                    ),
                ),
                ("container_id", models.CharField(blank=True, max_length=100)),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Container Job",
                "verbose_name_plural": "Container Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContainerExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_memory_usage",
                    models.PositiveIntegerField(
                        blank=True, help_text="Peak memory usage in bytes", null=True
                    ),
                ),
                (
                    "cpu_usage_percent",
                    models.FloatField(
                        blank=True, help_text="Average CPU usage percentage", null=True
                    ),
                ),
                ("stdout_log", models.TextField(blank=True)),
                ("stderr_log", models.TextField(blank=True)),
                (
                    "docker_log",
                    models.TextField(
                        blank=True, help_text="Docker daemon logs and events"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution",
                        to="container_manager.containerjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Container Execution",
                "verbose_name_plural": "Container Executions",
            },
        ),
        migrations.CreateModel(
            name="ContainerTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("docker_image", models.CharField(max_length=500)),
                (
                    "command",
                    models.TextField(
                        blank=True, help_text="Command to run in container (optional)"
                    ),
                ),
                ("working_directory", models.CharField(blank=True, max_length=500)),
                (
                    "memory_limit",
                    models.PositiveIntegerField(
                        blank=True, help_text="Memory limit in MB", null=True
                    ),
                ),
                (
                    "cpu_limit",
                    models.FloatField(
                        blank=True,
                        help_text="CPU limit (e.g., 1.5 for 1.5 cores)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(32.0),
                        ],
                    ),
                ),
                (
                    "timeout_seconds",
                    models.PositiveIntegerField(
                        default=3600, help_text="Maximum execution time in seconds"
                    ),
                ),
                (
                    "auto_remove",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically remove container after execution",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Container Template",
                "verbose_name_plural": "Container Templates",
            },
        ),
        migrations.AddField(
            model_name="containerjob",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="container_manager.containertemplate",
            ),
        ),
        migrations.AddField(
            model_name="containerjob",
            name="docker_host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="container_manager.dockerhost",
            ),
        ),
        migrations.CreateModel(
            name="EnvironmentVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=200)),
                ("value", models.TextField()),
                (
                    "is_secret",
                    models.BooleanField(
                        default=False, help_text="Mark as secret to hide value in logs"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environment_variables",
                        to="container_manager.containertemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Environment Variable",
                "verbose_name_plural": "Environment Variables",
                "unique_together": {("template", "key")},
            },
        ),
        migrations.CreateModel(
            name="NetworkAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("network_name", models.CharField(max_length=200)),
                (
                    "aliases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Network aliases for the container",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_assignments",
                        to="container_manager.containertemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Network Assignment",
                "verbose_name_plural": "Network Assignments",
                "unique_together": {("template", "network_name")},
            },
        ),
    ]
