# Generated by Django 5.2.4 on 2025-07-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerjob',
            name='clean_output',
            field=models.TextField(blank=True, help_text='Stdout with timestamps and metadata stripped'),
        ),
        migrations.AddField(
            model_name='containerjob',
            name='cpu_usage_percent',
            field=models.FloatField(blank=True, help_text='Average CPU usage percentage', null=True),
        ),
        migrations.AddField(
            model_name='containerjob',
            name='docker_log',
            field=models.TextField(blank=True, help_text='Docker daemon logs and events'),
        ),
        migrations.AddField(
            model_name='containerjob',
            name='max_memory_usage',
            field=models.PositiveIntegerField(blank=True, help_text='Peak memory usage in bytes', null=True),
        ),
        migrations.AddField(
            model_name='containerjob',
            name='stderr_log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='containerjob',
            name='stdout_log',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ContainerExecution',
        ),
    ]
