# Generated by Django 5.2.4 on 2025-07-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("container_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="containerjob",
            name="container_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
