# Generated by Django 5.2.4 on 2025-07-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("container_manager", "0002_alter_containerjob_container_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="dockerhost",
            name="auto_pull_images",
            field=models.BooleanField(
                default=True,
                help_text="Automatically pull Docker images that don't exist locally",
            ),
        ),
    ]
