# Generated by Django 5.2.4 on 2025-07-30 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container_manager', '0003_merge_template_into_job'),
    ]

    operations = [
        # Drop routing models tables in correct order (handling foreign key dependencies)
        # SQLite doesn't support CASCADE, so we drop in dependency order
        migrations.RunSQL(
            "DROP TABLE IF EXISTS container_manager_rulevalidationresult;",
            reverse_sql="-- Cannot reverse dropping table"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS container_manager_routingdecision;", 
            reverse_sql="-- Cannot reverse dropping table"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS container_manager_routingrule;",
            reverse_sql="-- Cannot reverse dropping table"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS container_manager_routingruleset;",
            reverse_sql="-- Cannot reverse dropping table"
        ),
    ]
