# Generated by Django 5.2.4 on 2025-07-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("container_manager", "0004_containerexecution_clean_output_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="containerjob",
            name="actual_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Actual execution cost in USD (if available)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="containerjob",
            name="estimated_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Estimated execution cost in USD",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="containerjob",
            name="executor_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Provider-specific data like regions, URLs, resource identifiers",
            ),
        ),
        migrations.AddField(
            model_name="containerjob",
            name="executor_type",
            field=models.CharField(
                choices=[
                    ("docker", "Docker"),
                    ("cloudrun", "Google Cloud Run"),
                    ("fargate", "AWS Fargate"),
                    ("scaleway", "Scaleway Containers"),
                    ("mock", "Mock (Testing)"),
                ],
                default="docker",
                help_text="Container execution backend to use for this job",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="containerjob",
            name="external_execution_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Cloud provider's execution/job ID (e.g., Cloud Run job name, Fargate task ARN)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="containerjob",
            name="preferred_executor",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Preferred executor type for this job (overrides routing rules)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="containerjob",
            name="routing_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Reason why this executor was chosen (for debugging/analytics)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="dockerhost",
            name="average_startup_time",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Average container startup time in seconds",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dockerhost",
            name="cost_per_hour",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Estimated cost per hour for this executor",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dockerhost",
            name="cost_per_job",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Estimated cost per job execution",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dockerhost",
            name="current_job_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Currently running job count (updated by worker process)",
            ),
        ),
        migrations.AddField(
            model_name="dockerhost",
            name="executor_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Executor-specific configuration (credentials, regions, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="dockerhost",
            name="executor_type",
            field=models.CharField(
                choices=[
                    ("docker", "Docker"),
                    ("cloudrun", "Google Cloud Run"),
                    ("fargate", "AWS Fargate"),
                    ("scaleway", "Scaleway Containers"),
                ],
                default="docker",
                help_text="Type of container executor this host represents",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="dockerhost",
            name="health_check_failures",
            field=models.PositiveIntegerField(
                default=0, help_text="Consecutive health check failures"
            ),
        ),
        migrations.AddField(
            model_name="dockerhost",
            name="last_health_check",
            field=models.DateTimeField(
                blank=True,
                help_text="Last successful health check timestamp",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dockerhost",
            name="max_concurrent_jobs",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Maximum number of concurrent jobs for this executor",
            ),
        ),
    ]
