# Generated by Django 5.2.4 on 2025-07-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_manager', '0004_remove_routing_models'),
    ]

    operations = [
        # Remove routing_reason field from ContainerJob
        migrations.RemoveField(
            model_name='containerjob',
            name='routing_reason',
        ),
        # Update preferred_executor help text (remove routing reference)
        migrations.AlterField(
            model_name='containerjob',
            name='preferred_executor',
            field=models.CharField(blank=True, choices=[('docker', 'Docker'), ('cloudrun', 'Google Cloud Run'), ('fargate', 'AWS Fargate'), ('scaleway', 'Scaleway Containers'), ('mock', 'Mock (Testing)')], default='', help_text='Preferred executor type for this job', max_length=50),
        ),
        # Note: Routing model operations removed - tables already dropped in 0004_remove_routing_models
    ]
