# Generated by Django 5.2.4 on 2025-07-26 13:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("container_manager", "0005_add_multi_executor_support"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutingRuleSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ab_test_enabled", models.BooleanField(default=False)),
                (
                    "ab_test_percentage",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage of jobs to apply this ruleset to (0-100)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Routing Rule Set",
                "verbose_name_plural": "Routing Rule Sets",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RoutingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "condition",
                    models.TextField(
                        help_text="Python expression that evaluates to True/False"
                    ),
                ),
                (
                    "target_executor",
                    models.CharField(
                        choices=[
                            ("docker", "Docker"),
                            ("cloudrun", "Cloud Run"),
                            ("fargate", "AWS Fargate"),
                            ("mock", "Mock (Testing)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=100, help_text="Lower numbers = higher priority"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("execution_count", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("last_executed", models.DateTimeField(blank=True, null=True)),
                (
                    "ruleset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="container_manager.routingruleset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Routing Rule",
                "verbose_name_plural": "Routing Rules",
                "ordering": ["priority", "created_at"],
                "unique_together": {("ruleset", "name")},
            },
        ),
        migrations.CreateModel(
            name="RuleValidationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_case", models.CharField(max_length=100)),
                ("expected_result", models.BooleanField()),
                ("actual_result", models.BooleanField()),
                ("passed", models.BooleanField()),
                ("error_message", models.TextField(blank=True)),
                ("tested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="container_manager.routingrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rule Validation Result",
                "verbose_name_plural": "Rule Validation Results",
                "ordering": ["-tested_at"],
            },
        ),
        migrations.CreateModel(
            name="RoutingDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_id", models.UUIDField()),
                ("selected_executor", models.CharField(max_length=50)),
                ("decision_reason", models.TextField()),
                ("evaluated_rules", models.JSONField(default=list)),
                ("job_context", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("execution_time_ms", models.FloatField(blank=True, null=True)),
                ("is_ab_test", models.BooleanField(default=False)),
                ("ab_test_group", models.CharField(blank=True, max_length=50)),
                (
                    "rule_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="container_manager.routingrule",
                    ),
                ),
                (
                    "ruleset_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="container_manager.routingruleset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Routing Decision",
                "verbose_name_plural": "Routing Decisions",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["job_id"], name="container_m_job_id_32ec26_idx"
                    ),
                    models.Index(
                        fields=["selected_executor"],
                        name="container_m_selecte_5af052_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="container_m_timesta_24a59f_idx"
                    ),
                ],
            },
        ),
    ]
