# Generated by Django 5.2.4 on 2025-07-30 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container_manager', '0005_remove_routing_reason_field'),
    ]

    operations = [
        # Drop NetworkAssignment table (deprecated - replaced by network_configuration JSONField)
        migrations.RunSQL(
            "DROP TABLE IF EXISTS container_manager_networkassignment;",
            reverse_sql="-- Cannot reverse dropping table"
        ),
        # Note: Routing models already dropped in previous migrations
    ]
