# Generated by Django 5.1.4

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container_manager', '0006_remove_network_assignment_model'),
    ]

    operations = [
        # Add foreign key to EnvironmentVariableTemplate
        migrations.AddField(
            model_name='containerjob',
            name='environment_template',
            field=models.ForeignKey(
                blank=True,
                help_text='Environment variable template to use as base configuration',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='container_manager.environmentvariabletemplate'
            ),
        ),
        
        # Change override_environment to TextField
        migrations.AlterField(
            model_name='containerjob',
            name='override_environment',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Environment variable overrides, one per line in KEY=value format. These override any variables from the template. Example:\nDEBUG=true\nWORKER_COUNT=4',
                verbose_name='Environment Variable Overrides'
            ),
        ),
        
        # Remove environment_variables JSONField
        migrations.RemoveField(
            model_name='containerjob',
            name='environment_variables',
        ),
        
        # Remove template field
        migrations.RemoveField(
            model_name='containerjob',
            name='template',
        ),
    ]