# Generated by Django 5.1.4

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container_manager', '0007_refactor_containerjob_environment_variables'),
    ]

    operations = [
        # Drop the ContainerTemplate table completely
        migrations.RunSQL(
            "DROP TABLE IF EXISTS container_manager_containertemplate;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]