# Generated by Django 5.2.4 on 2025-07-31 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container_manager', '0008_remove_containertemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containerjob',
            name='executor_type',
        ),
        migrations.RemoveField(
            model_name='containerjob',
            name='preferred_executor',
        ),
    ]