# Generated by Django 5.2.4 on 2025-07-26 15:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_manager', '0009_create_migration_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='CostBudget',
        ),
        migrations.RemoveField(
            model_name='costrecord',
            name='cost_profile',
        ),
        migrations.RemoveField(
            model_name='costrecord',
            name='resource_usage',
        ),
        migrations.DeleteModel(
            name='ExecutorPerformanceMetric',
        ),
        migrations.DeleteModel(
            name='ExecutorPerformanceSummary',
        ),
        migrations.RemoveField(
            model_name='jobmigration',
            name='migration_plan',
        ),
        migrations.RemoveField(
            model_name='migrationvalidation',
            name='job_migration',
        ),
        migrations.RemoveField(
            model_name='migrationcheckpoint',
            name='migration_plan',
        ),
        migrations.RemoveField(
            model_name='migrationmetrics',
            name='migration_plan',
        ),
        migrations.RemoveField(
            model_name='migrationplan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='performancerecommendation',
            name='based_on_bottleneck',
        ),
        migrations.RemoveField(
            model_name='performancerecommendation',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='containerjob',
            name='actual_cost',
        ),
        migrations.RemoveField(
            model_name='containerjob',
            name='cost_currency',
        ),
        migrations.RemoveField(
            model_name='containerjob',
            name='cost_profile_id',
        ),
        migrations.RemoveField(
            model_name='containerjob',
            name='cost_tracking_started_at',
        ),
        migrations.RemoveField(
            model_name='containerjob',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='containerjob',
            name='preferred_executor',
        ),
        migrations.RemoveField(
            model_name='containerjob',
            name='routing_reason',
        ),
        migrations.RemoveField(
            model_name='dockerhost',
            name='average_startup_time',
        ),
        migrations.RemoveField(
            model_name='dockerhost',
            name='cost_per_hour',
        ),
        migrations.RemoveField(
            model_name='dockerhost',
            name='cost_per_job',
        ),
        migrations.RemoveField(
            model_name='dockerhost',
            name='current_job_count',
        ),
        migrations.RemoveField(
            model_name='dockerhost',
            name='health_check_failures',
        ),
        migrations.RemoveField(
            model_name='dockerhost',
            name='last_health_check',
        ),
        migrations.AddField(
            model_name='containerjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dockerhost',
            name='weight',
            field=models.PositiveIntegerField(default=100, help_text='Routing weight (higher = more preferred, 1-1000)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='containerjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CostProfile',
        ),
        migrations.DeleteModel(
            name='CostRecord',
        ),
        migrations.DeleteModel(
            name='ResourceUsage',
        ),
        migrations.DeleteModel(
            name='JobMigration',
        ),
        migrations.DeleteModel(
            name='MigrationValidation',
        ),
        migrations.DeleteModel(
            name='MigrationCheckpoint',
        ),
        migrations.DeleteModel(
            name='MigrationMetrics',
        ),
        migrations.DeleteModel(
            name='MigrationPlan',
        ),
        migrations.DeleteModel(
            name='PerformanceBottleneck',
        ),
        migrations.DeleteModel(
            name='PerformanceRecommendation',
        ),
    ]
