# Generated by Django 5.2.4 on 2025-07-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_manager', '0010_simplify_models_add_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='containertemplate',
            name='environment_variables_text',
            field=models.TextField(blank=True, help_text='Environment variables, one per line in KEY=value format. Example:\nDEBUG=true\nAPI_KEY=secret123\nTIMEOUT=300', verbose_name='Environment Variables'),
        ),
        migrations.AlterField(
            model_name='containerjob',
            name='executor_metadata',
            field=models.JSONField(blank=True, default=dict, help_text="Executor-specific runtime data and identifiers. Examples:\n• Docker: {'container_name': 'my-job-123', 'network': 'bridge'}\n• Cloud Run: {'job_name': 'job-abc123', 'region': 'us-central1', 'project': 'my-project'}\n• AWS Fargate: {'task_arn': 'arn:aws:ecs:...', 'cluster': 'my-cluster', 'task_definition': 'my-task:1'}\n• Custom: Any JSON data your executor needs to track or reference the job"),
        ),
        migrations.AlterField(
            model_name='containerjob',
            name='override_command',
            field=models.TextField(blank=True, help_text='Override the template\'s default command. Examples:\n• Single command: python main.py --config=prod\n• Shell command: bash -c "echo Starting...; python app.py; echo Done"\n• Multi-step: bash -c "pip install -r requirements.txt && python manage.py migrate && python manage.py runserver"\n• Script execution: /bin/sh /scripts/deploy.sh --environment=staging\n• Data processing: python process_data.py --input=/data/input.csv --output=/data/results.json\nLeave blank to use the template\'s default command.'),
        ),
        migrations.AlterField(
            model_name='containerjob',
            name='override_environment',
            field=models.JSONField(blank=True, default=dict, help_text='Additional or override environment variables for this specific job. Examples:\n• Simple config: {"DEBUG": "true", "LOG_LEVEL": "info"}\n• Database: {"DB_HOST": "prod-db.company.com", "DB_NAME": "prod_db"}\n• API keys: {"API_KEY": "sk-1234567890", "WEBHOOK_URL": "https://api.company.com/webhook"}\n• File paths: {"INPUT_FILE": "/data/batch_2024.csv", "OUTPUT_DIR": "/results/batch_001"}\n• Feature flags: {"ENABLE_FEATURE_X": "true", "USE_NEW_ALGORITHM": "false"}\nThese merge with template environment variables, with job values taking precedence.'),
        ),
        migrations.AlterField(
            model_name='dockerhost',
            name='executor_config',
            field=models.JSONField(blank=True, default=dict, help_text="Executor-specific configuration for this host. Examples:\n• Docker: {'base_url': 'tcp://host:2376', 'tls_verify': true}\n• Cloud Run: {'project': 'my-project', 'region': 'us-central1', 'service_account': 'sa@project.iam'}\n• AWS Fargate: {'cluster': 'my-cluster', 'subnets': ['subnet-123'], 'security_groups': ['sg-456']}\n• General: Any JSON config your custom executor implementation needs"),
        ),
    ]
