# Generated by Django 5.2.4 on 2025-07-26 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container_manager', '0011_add_environment_variables_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnvironmentVariable',
        ),
    ]
