# Generated by Django 5.2.4 on 2025-07-27 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_manager', '0012_remove_environment_variable_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containertemplate',
            name='environment_variables_text',
        ),
        migrations.AddField(
            model_name='containertemplate',
            name='override_environment_variables_text',
            field=models.TextField(blank=True, help_text='Environment variable overrides, one per line in KEY=value format. These override any variables from the template. Example:\nDEBUG=true\nWORKER_COUNT=4', verbose_name='Environment Variable Overrides'),
        ),
        migrations.CreateModel(
            name='EnvironmentVariableTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('environment_variables_text', models.TextField(blank=True, help_text='Environment variables, one per line in KEY=value format. Example:\nDEBUG=true\nAPI_KEY=secret123\nTIMEOUT=300', verbose_name='Environment Variables')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Environment Variable Template',
                'verbose_name_plural': 'Environment Variable Templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='containertemplate',
            name='environment_template',
            field=models.ForeignKey(blank=True, help_text='Optional environment variable template to use as base configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, to='container_manager.environmentvariabletemplate'),
        ),
    ]
