# Generated by Django 5.2.4 on 2025-07-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_manager', '0013_add_environment_variable_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerjob',
            name='preferred_executor',
            field=models.CharField(blank=True, choices=[('docker', 'Docker'), ('cloudrun', 'Google Cloud Run'), ('fargate', 'AWS Fargate'), ('scaleway', 'Scaleway Containers'), ('mock', 'Mock (Testing)')], default='', help_text='Preferred executor type for this job (used by routing logic)', max_length=50),
        ),
        migrations.AddField(
            model_name='containerjob',
            name='routing_reason',
            field=models.TextField(blank=True, default='', help_text='Explanation of why this executor was chosen for this job'),
        ),
        migrations.AddField(
            model_name='dockerhost',
            name='current_job_count',
            field=models.PositiveIntegerField(default=0, help_text='Current number of running jobs on this host'),
        ),
        migrations.AddField(
            model_name='dockerhost',
            name='health_check_failures',
            field=models.PositiveIntegerField(default=0, help_text='Number of consecutive health check failures'),
        ),
    ]
