# Generated by Django 5.2.4 on 2025-07-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_manager', '0014_add_missing_test_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerhost',
            name='last_health_check',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last health check', null=True),
        ),
    ]
