# Generated by Django 5.2.4 on 2025-07-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_manager', '0015_add_last_health_check_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerjob',
            name='execution_id',
            field=models.CharField(blank=True, default='', help_text='Unified execution identifier for all executor types', max_length=255),
        ),
    ]
