# Generated by Django 5.2.4 on 2025-07-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container_manager', '0016_add_unified_execution_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DockerHost',
            new_name='ExecutorHost',
        ),
        migrations.AlterModelOptions(
            name='executorhost',
            options={'verbose_name': 'Executor Host', 'verbose_name_plural': 'Executor Hosts'},
        ),
    ]
